ballerina-platform/module-ballerina-udp

udp-ballerina/tests/udp_client_tests.bal
> Refactor the code to use new log API
=> Refactor the code to use new log API

.github/workflows/build-main.yml, .github/workflows/stdlib-workflow-trigger.yml
=> Rename the master branch to main

.github/workflows/publish-release.yml
> Post release PR; base changed from default master branch to main branch
=> Change base from master to main

udp-ballerina/init.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/ModuleUtils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SelectorManager.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketConstants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketUtils.java
> Remove hard coded ballerina version in java code
=> Remove hard coded ballerina version in java code

gradle.properties
=> Sync master after Release 0.8.0

udp-ballerina/connectionless_client.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SelectorManager.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketConstants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketUtils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/endpoint/ConnectionlessClientActions.java
> API changed according to the proposed design [doc](https://docs.google.com/document/d/1Laub9_sntPq0NcZXB1Vn_FzuJZJH9gUdRribd8pnwuc/edit?usp=sharing)
=> Connectionless client API changes

udp-native/src/main/java/org/ballerinalang/stdlib/udp/ReadPendingCallback.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SelectorManager.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketConstants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/endpoint/ConnectionlessClientActions.java
> update the java documentation and the code refactored by removing the DEFAULT_EXPECTED_READ_LENGTH constant
=> update java documentation and code refactored

udp-ballerina/connectionless_client.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SelectorManager.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/endpoint/ConnectionlessClientActions.java
> Format the ballerina doc and Error messages
=> Format ballerina doc and error messages

udp-ballerina/connect_client.bal, udp-ballerina/tests/connect_client_tests.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/ReadPendingCallback.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SelectorManager.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/SocketConstants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/endpoint/ConnectClientActions.java
> Implementing connection oriented UDP client (client which only read and write data to the connected remote host)
=> Implementation of connection oriented UDP client

udp-ballerina/build.gradle
> gradle configuration to skip the test (./gradlew clean -x test )
=> update gradle ballerinaTest and ballerinaBuild tasks

udp-ballerina/connectionless_client.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpFactory.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/Client.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/ConnectClient.java
> thread count added for eventLoopGroup, and ConnectionlessClient renamed to Client
=> Added thread count to eventLoopGroup

udp-ballerina/caller.bal, udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/listener.bal, udp-ballerina/service.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal, udp-ballerina/tests/mock_servers.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Constants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Dispatcher.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/MethodDispatcher.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpCallback.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpConnectClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpFactory.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListener.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListenerHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpService.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Utils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/Client.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/ConnectClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativelistener/Caller.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativelistener/Listener.java
> udp:Listener implemented according to the proposed design and Implemented the backed using netty framework
=> UDP listener implementation

udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal
=> Fix testerina function configs

udp-ballerina/caller.bal, udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/listener.bal, udp-ballerina/service.bal, udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal, udp-ballerina/tests/mock_servers.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Dispatcher.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpConnectClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListener.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListenerHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpService.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Utils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativelistener/Listener.java
This pull request
> Update byte[] and Datagram as readonly on receive methods
> Remove timeout from listener implementation
> Update Listener attach() method name parameter type to ()
> Remove service object methods to make them as optional
=> Refactor the code

udp-ballerina/build.gradle
$subject.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Update ballerina command to bal command

udp-ballerina/Package.md
=> Update Package.md file

udp-ballerina/caller.bal, udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/init.bal, udp-ballerina/listener.bal, udp-ballerina/tests/connectionless_client_tests.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

udp-ballerina/Ballerina.toml, udp-ballerina/Dependencies.toml, udp-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

udp-ballerina/build.gradle
> Configure gradle to revert Dependencies.toml
=> Configure gradle to revert Dependencies.toml

gradle.properties
=> [Automated] Update lang version to 2.0.0-alpha-SNAPSHOT

.github/workflows/build-main.yml, .github/workflows/pull-request.yml, gradle.properties, udp-ballerina/build.gradle
=> Enable code coverage

README.md
> Add URL for api-docs and BBE
=> Add URL for api-docs and BBE

README.md, udp-ballerina/Package.md
> Update README.md and Package.md files
=> Update README.md and Package.md files

.github/workflows/publish-release.yml, README.md, build.gradle, gradle.properties, udp-ballerina/build.gradle
> Enable Publishing to Ballerina Central on Release
=> Enable Publishing to Ballerina Central on Release

build.gradle
> Update Module version in build.gradle
=> Update Module version in build.gradle

build.gradle, udp-ballerina/build.gradle
> Re-order Build Tasks to Publish to the Ballerina Central
=> Re-order Build Tasks to Publish to the Ballerina Central

udp-ballerina/build.gradle
=> Remove publishing testable jar and exec artifacts

udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Constants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/Client.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/ConnectClient.java
> Replace 'int timeoutInMillis' with 'decimal timeout'
=> Replace 'int timeoutInMillis' with 'decimal timeout'

udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal, udp-ballerina/tests/mock_servers.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpConnectClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Utils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativeclient/Client.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativelistener/Listener.java
> This PR introduces few tests
=> Add tests to validate connected listener functionality, invalid value for interface name

udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListener.java
> Assign channel only when future is success
=> Assign channel only when future is success

README.md
=> Add Codecov batch in README

udp-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

udp-ballerina/Package.md, udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal, udp-ballerina/tests/mock_servers.bal
> Update log API usages with latest changes
=> Update log api usages with latest changes

udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/listener.bal, udp-ballerina/tests/mock_servers.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Constants.java
=> Rename ListenerConfig and ClientConfig to ListenerConfiguration and ClientConfiguration 

udp-ballerina/tests/connect_client_tests.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/listener_tests.bal, udp-ballerina/tests/mock_servers.bal
> Removes getString() function and replace it with string:fromBytes()
> replace `checkpanic socketClient->close()` with `check socketClient->close()`
> replace conditional checking of errors with `check` keyword
from tests
=> Update tests by replacing checkpanic with check, replace getString with th string:fromBytes()

udp-ballerina/socket_error.bal, udp-ballerina/tests/connectionless_client_tests.bal, udp-ballerina/tests/mock_servers.bal, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Constants.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Dispatcher.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClient.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpClientHandler.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/UdpListener.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/Utils.java, udp-native/src/main/java/org/ballerinalang/stdlib/udp/nativelistener/Listener.java, udp-test-utils/src/main/java/org/ballerinalang/stdlib/udp/testutils/MockServerUtils.java
> Replace 'readonly & Error err' with 'Error err'
> Remove ReadTimedOutError, GenericError
=> Remove ReadTimedOutError, GenericError

codecov.yml
=> Remove path fixing in Codecov.yml File

udp-ballerina/listener.bal, udp-ballerina/tests/connectionless_client_tests.bal
=> Remove variable from BeforeSuite and AfterSuite

build.gradle, udp-ballerina/build.gradle
=> Strip stdlib dependency version

udp-compiler-plugin-tests/build.gradle
=> Fix compiler plugin build

udp-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, udp-ballerina/Ballerina.toml, udp-ballerina/build.gradle
Standardize build script of Ballerina module
=> Apply Gradle Ballerina plugin for Ballerina module build script

udp-ballerina/build.gradle
=> Fix toml version being published with timestamp

gradle.properties, udp-ballerina/build.gradle
=> Move plugin to stable version

README.md, udp-ballerina/Module.md, udp-ballerina/Package.md, udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal, udp-ballerina/listener.bal
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1352
=> Update docs in UDP module

udp-ballerina/connect_client.bal, udp-ballerina/connectionless_client.bal
=> Make UDP clients isolated

README.md, udp-ballerina/Module.md, udp-ballerina/Package.md
=> Fix Documentation

udp-ballerina/Package.md
Relates to ballerina-platform/ballerina-standard-library#1462
=> Update Package.md links into HTML format

udp-ballerina/Module.md
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1554
=> Change bullet style to be compatible with other docs

ballerina/Dependencies.toml, gradle.properties
=> Fix a dependency related build failure

.gitignore, changelog.md, docs/spec/spec.md
1. Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2197
2. Add auto-generated files/directories by VSCode into `.gitignore`
=> Add UDP library specification and remove auto-generated files/directories by VSCode

.github/workflows/build-timestamped-master.yml, ballerina/tests/mock_servers.bal
1. Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2362
2. Avoid warnings in build due to unused variables
=> Reduce warnings and skip master build for `.md` file changes

ballerina/service.bal, changelog.md, compiler-plugin-tests/src/test/resources/ballerina_sources/sample_package_10/modules/module/listener.bal, gradle.properties
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398
=> Make UDP service-type distinct

compiler-plugin-tests/build.gradle, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/udp/compiler/CompilerPluginTest.java, gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
=> Update gradle plugin version

.github/workflows/publish-release.yml, ballerina/Dependencies.toml
Related to ballerina-platform/ballerina-standard-library#2426
=> Add a cleaning phase to the GitHub release action

docs/spec/spec.md
=> Update the introduction of the spec

.github/workflows/build-timestamped-master.yml, .github/workflows/process-load-test-result.yml, .github/workflows/trigger-load-tests.yml, .gitignore, codecov.yml, load-tests/file_server/deployment/ingress.yaml, load-tests/file_server/deployment/kustomization.yaml, load-tests/file_server/results/summary.csv, load-tests/file_server/scripts/load_test/Ballerina.toml, load-tests/file_server/scripts/load_test/main.bal, load-tests/file_server/scripts/post_run.sh, load-tests/file_server/scripts/run.sh, load-tests/file_server/src/Ballerina.toml, load-tests/file_server/src/Cloud.toml, load-tests/file_server/src/main.bal, load-tests/file_server/src/resources/test.txt
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2117
=> Add load test to the udp module

load-tests/file_server/src/Cloud.toml
=> Copy the file to the container

load-tests/file_server/src/main.bal
=> Add some logs to debug

load-tests/file_server/deployment/deployment-patch.yaml, load-tests/file_server/deployment/kustomization.yaml
=> Enable logs

load-tests/file_server/src/main.bal
=> Increase the load test duration to 1 hour

docs/spec/spec.md
=> Update introduction of the specification

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, examples/simple-file-server/server/udp_file_server.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2671
=> Fix the udp file server example

README.md, ballerina/Package.md
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2748
=> Update doc titles to sentence case

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update dependencies to latest timestamp versions

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update to snapshot version

.github/workflows/central-publish.yml, gradle.properties
=> Allow central publish action to publish to multiple environments

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3128
=> Update std libs with 2201.2.0 lang version

gradle.properties
=> Update lang version to RC1

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
$title
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3117
=> Add details for the native jar

gradle.properties
=> Update to latest timestamp versions

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/udp-native/reflect-config.json
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3407
=> Add native image build configurations

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/udp/Dispatcher.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Fix failing build for type reference support 

ballerina/Dependencies.toml, gradle.properties
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Update versions for type-reference-support

.github/workflows/pull-request.yml, ballerina/Dependencies.toml
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3988
=> Add Codecov upload retry step for for UDP module

ballerina/Dependencies.toml, gradle.properties
=> Update lang timestamp version

README.md
=> Update last commit badge link in README

.github/workflows/process-load-test-result.yml, .github/workflows/pull-request.yml, .github/workflows/trigger-load-tests.yml
Related issue : https://github.com/ballerina-platform/ballerina-standard-library/issues/4098
=> Add codecov token to pr build workflow and add workflow calls to load test

examples/simple-file-server/README.md
=> Update meta info of examples

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/udp/Dispatcher.java
This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344
=> Fix object getType() API usage

.github/workflows/build-with-bal-test-graalvm.yml, README.md, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
=> Incorperate native build command change

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4568
=> Mark udp module as GraalVM compatible

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Bump patch version

examples/simple-file-server/UDP File Server & Client Example in Ballerina.md
This is for SEO purposes so the examples get listed on search engines.
=> Update README file of the example

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update version to snapshot version

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, ballerina/Dependencies.toml
Part of: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778
=> Migrate workflows to reuse workflows from ballerina-standard-library repo

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, gradle.properties
=> [2201.10.x] Bump module version

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Update Dependency Versions for U11

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update versions for Update 12
